config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 「SPA用のrouting」
  root 'home#index' #'groups#index'

  #group関連
  get '/groups/', to: 'home#index'
  get '/groups/new', to: 'home#index'
  get '/groups/:id', to: 'home#index'
  get '/groups/:id/detail', to: 'home#index'
  get '/groups/:id/events', to: 'home#index'
  get '/groups/:id/member', to: 'home#index'
  get '/groups/:id/edit', to: 'home#index'

  #approval関連
  get '/groups/:id/approval', to: 'home#index'
  get '/groups/:id/joins/:join_id/permit', to: 'home#index'

  #evnet関連
  get '/groups/:id/events/new', to: 'home#index'
  get '/groups/:id/events/:event_id', to: 'home#index'
  get '/groups/:id/events/:event_id/edit', to: 'home#index'

  #join関連
  get '/groups/:id/joins/new', to: 'home#index'
  get '/groups/:id/joins/:join_id/edit', to: 'home#index'

  #user関連
  get '/login', to: 'home#index'

  get '/users/', to: 'home#index'
  get '/users/new', to: 'home#index'
  get '/users/:id', to: 'home#index'
  get '/users/:id/profile', to: 'home#index'
  get '/users/:id/application', to: 'home#index'
  get '/users/:id/edit', to: 'home#index'
  get '/users/:id/event', to: 'home#index'
  get '/users/:id/favorite', to: 'home#index'
  
  #application関連
  get '/users/:id/application', to: 'home#index'

  #「API用のrouting」

  # resources :users
  resources :answers #, :only => [:show, :edit ] 

  namespace :api, {format: 'json'} do
    namespace :v1 do

      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/login', to: 'sessions#destroy'
      post 'guest_login', to: "users#guest_login" #簡単ログイン用に追加 1/20

      resources :users

      resources :answers #, :only => [:show, :edit ]  //ここを追記

      resources :groups do #do
        #member do 2/6 削除 join controller に移行
          #get :join
        #end

        # resources :favorites , only: [:create, :destroy]
        get '/favorites', to: 'favorites#index'
        post 'favorites', to: 'favorites#create'
        delete 'favorites', to: 'favorites#destroy'

        resources :joins, param: :join_id do #2/6 join controller作成のため追記
          member do 
            get :permit
            delete :leave #3/2 join leave処理の追加
            delete :deny #9/2 申請拒否の追加
          end 
        end
        resources :events, param: :event_id # 7/15 GoupEventで一覧が必要なためコメントアウト, :except => [:index ] 
      end

    end
  end

end

app/models/user.rb
class User < ApplicationRecord

# ==============画像uploader機能 ================================
  mount_uploader :image, ImageUploader
# ==============バリデーション ================================
  #ユーザー認証のpassword用の設定
  has_secure_password
  #ユーザー認証登録時に必要な情報は未入力は不可
  with_options presence: true do
    validates :name
    validates :email
    validates :password_digest
  end
  #emailは重複不可
  validates :email, uniqueness: true

# ==============アソシエーション ================================
  #favorite用 (多対多)
  has_many :favorites, dependent: :destroy
  has_many :groups, through: :favorites
  #join用 (多対多)
  has_many :joins, dependent: :destroy
  has_many :groups, through: :joins
  #Answer用 (多対多)
  has_many :answers, dependent: :destroy
  has_many :events, through: :answers
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  protect_from_forgery #追記
  before_action :logged_in_user, only: %i[ edit show update destroy ] #このアクションはログイン後しか実行できない
  before_action :set_target_user, only: %i[show edit update destroy]
  before_action :master_user, only: %i[ edit update destroy] #自分自身でないと操作できないアクション
  before_action :check_guest, only: %i[ update destroy] #ゲストユーザーは編集,削除不可 
  
  def new #アカウントがないので新規作成させる
    @user = User.new
    render json: {user: @user }
  end

  def create
    user = User.new(user_params)
    if user.save
      render json: user
    else
      # render json: { errors: user.errors.full_messages }, status: 400
      render json: user
    end
  end

  def show
    #--------------------N+1改善ver--------------------
    #申請依頼中のgroup一覧
    @applications = Join.includes(:group).where(user_id: @user.id).where(level: 2)
    @applicaiton_groups = []
    @applications.each do |application|
        @applicaiton_groups.push(application.group)
    end

    @applicaiton_groups_count = @applicaiton_groups.length

    #Mygroup一覧のための準備
    @user_joins = Join.includes(:group).where(user_id: @user.id).where(level: 1)
    @user_groups = []
    @user_joins.each do |user_join|
      @user_groups.push(user_join.group)
    end

    #参加予定eventの取得
    @user_answers = Answer.includes(:event).where(user_id: @user.id)
    @user_join_answers = @user_answers.where("answer= '○'")
    @join_events = []
    @user_join_answers.each do |user_join_answer|
      @join_events.push(user_join_answer.event)
    end

    #お気に入りグループの取得
    @user_favorites = Favorite.includes(:group).where(user_id: @user.id)
    @user_favorites_groups = []
    @user_favorites.each do |user_favorite|
      @user_favorites_groups.push(user_favorite.group)
    end

    render json: {
      user: @user, 
      applications: @applications, 
      applicaiton_groups: @applicaiton_groups, 
      user_groups: @user_groups, 
      join_events: @join_events, 
      user_favorites_groups: @user_favorites_groups, 
      user_join_answers: @user_join_answers, 
      applicaiton_groups_count: @applicaiton_groups_count 
    }

    #--------------------元々のコードたち--------------------
    #申請中のデータ
    # @applications2 = Join.where(user_id: @user.id).where(level: '2')
    # @applicaiton_groups2 = []
    # for @application2 in @applications2 do
    #   @applicaiton_group2 = Group.find_by(id: @application2.group_id)
    #   @applicaiton_groups2.push(@applicaiton_group2)
    # end

    #my group一覧のための準備
    # @user_joins2=  @user.joins.where(level: 1)
    # @user_groups2 = []
    # for @user_join2 in @user_joins2 do
    #   @user_group2 = Group.find_by(id: @user_join2.group_id)
    #   @user_groups2.push(@user_group2)
    # end

    # #参加予定eventの取得
    # @user_answers2 = @user.answers #.where("answer = '○'")
    # @user_join_answers2 = @user_answers2.where("answer= '○'")
    # @join_events2 = []
    # for @user_join_answer2 in @user_join_answers2 do
    #   @join_event2 = @user_join_answer2.event
    #   @join_events2.push(@join_event2)
    # end
    
    # #お気に入りグループの取得
    # @user_favorites2 = @user.favorites
    # @user_favorites_groups2 = []
    # for @user_favorite2 in @user_favorites2 do
    #   @user_favorites_group2 = Group.find_by(id: @user_favorite2.group_id)
    #   @user_favorites_groups2.push(@user_favorites_group2)
    # end

    #--------------------ここで検証--------------------
    # @bool = false
    # if @applicaiton_groups2 == @applicaiton_groups && @user_favorites_groups2 === @user_favorites_groups
    #   @bool = true
    # end

    # render json: { bool: @bool, 
    #             }

    # render json: {user: @user, applications: @applications, applicaiton_groups: @applicaiton_groups, user_groups: @user_groups, join_events: @join_events, user_favorites_groups: @user_favorites_groups }

  end

  def edit
    render json: {user: @user, current_user: current_user }
  end

  def update
    if @user.update(user_params)
      # render json: @user, status: :created
      render json: {user: @user }
    else
      # render json: { status: 'SUCCESS', message: 'Not updated', data: @user.errors }
      render json: {user: @user }
    end
  end

  def destroy
    @groups = @user.groups.all #userに所属するuserを配列で取得
    @groups.each do |check_group|
      if check_group.adminuser_id == @user.id then
        check_group.destroy
      end
    end

    @user.destroy
    # render json: { status: 'SUCCESS', message: 'Deleted the user', data: @user }
    render json: {user: @user }
  end

  #ゲストユーザーログイン機能 1/20追記
  def guest_login
    user = User.find_or_create_by(email: 'guest@example.com')
    user.name = "GuestUser"
    user.password = SecureRandom.urlsafe_base64
    user.save if !user.id #idがない場合、DBに保存してIDを生成
    session[:user_id] = user.id
    # render json: user, status: :created
    render json: { user: user }
    # redirect_to groups_path, flash: { notice: "「ゲストユーザー」としてログインしました" }
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmationm, :image, :image_cache, :sex, :age, :birthplace , :introduction )
  end

  def set_target_user
    @user = User.find(params[:id])
  end
  
  #master_user(自分のアカウント)でないと戻す処理
  def master_user
    unless @user.id == current_user.id
      redirect_back(fallback_location: root_path) #直接urlに入力してきたユーザーは戻す
    end
  end

  #ゲストユーザーは変更・削除できない使用 1/20追加
  def check_guest
    if @user.email == 'guest@example.com'
      redirect_to root_path, flash: { notice: "「ゲストユーザー」は変更・削除できません" }
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[ edit show update destroy ] #このアクションはログイン後しか実行できない
  before_action :set_target_user, only: %i[show edit update destroy]
  before_action :master_user, only: %i[ edit update destroy] #自分自身でないと操作できないアクション
  before_action :check_guest, only: %i[update destroy] #ゲストユーザーは編集,削除不可

  #アカウントがないので新規作成させる
  def new
    @user = User.new
  end

  def create
    user = User.new(user_params)
    if user.save
      flash[:notice] = "「#{user.name}」を作成しました"
      log_in user #アカウント作成と同時にログインする
      redirect_to  user_path(user)
    else
  #フォームの入力エラーを起こした際のエラー表示を取得するための処理
      redirect_to new_user_path, flash: {
        user: user,
        error_messages: user.errors.full_messages
      }
    end
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user)
    else
  #フォームの入力エラーを起こした際のエラー表示を取得するための処理
      redirect_to edit_user_path, flash: {
        user: @user,
        error_messages: @user.errors.full_messages
    }
    end
  end

  def destroy
    @groups = @user.groups.all #userに所属するuserを配列で取得
    @groups.each do |check_group|
      if check_group.adminuser_id == @user.id then
        check_group.destroy
      end
    end

    @user.destroy
    redirect_to groups_path, flash: { notice: "「#{@user.name}」が削除されました"}
  end

  #ゲストユーザーログイン機能 1/20追記
  def guest_login
    user = User.find_or_create_by(email: 'guest@example.com')
    user.name = "GuestUser"
    user.password = SecureRandom.urlsafe_base64
    user.save if !user.id #idがない場合、DBに保存してIDを生成
    session[:user_id] = user.id
    redirect_to groups_path, flash: { notice: "「ゲストユーザー」としてログインしました" }
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmationm, :image, :image_cache)
  end

  def set_target_user
    @user = User.find(params[:id])
  end
  
  #master_user(自分のアカウント)でないと戻す処理
  def master_user
    unless @user.id == current_user.id
      redirect_back(fallback_location: root_path) #直接urlに入力してきたユーザーは戻す
    end
  end

  #ゲストユーザーは変更・削除できない使用 1/20追加
  def check_guest
    if @user.email == 'guest@example.com'
      redirect_to root_path, flash: { notice: "「ゲストユーザー」は変更・削除できません" }
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/user_show/_events.html.erb
  <!-- 所属するイベントを情報を表示 -->
<% user.events.each_with_index do |user_event| %>
<% @event_group = Group.find(user_event.group_id) %>
    <div class="card my-3" style="max-width: 500px;">
      <%= link_to group_path(@event_group) do %>
        <div class="row no-gutters">
          <div class="col-6" style="max-width: 150px;">

            <%# 画像が有る場合 %>
            <% if @event_group.image? %>
              <%= image_tag @event_group.image.thumb.url, class: "card-img", alt:"..." %>
            <%# 画像が無い場合 %>
            <% else %>
              <img src= <%="/assets/group#{1}.png"%> class="card-img" alt="...">
            <% end %>

          </div>
          <div class="col-6">
            <div class="card-body">
              <h4 class="card-title"><%= user_event.place %></h4>
              <p class="card-text"><%= user_event.date.strftime( "%-m/%-d" ) %></p>
                <% time_s = user_event.starttime.strftime( "%H:%M" ) %> <%# 開始時間をtime_sに格納%>
                <% time_f = user_event.finishtime.strftime( "%H:%M" ) %> <%# 開始時間をtime_fに格納%>
              <p class="card-text"><%= "#{time_s}~#{time_f}" %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>  
<% end %>

app/views/users/user_show/_groups.html.erb
  <!-- 所属するグループを情報を表示 -->
<% Join.where(user_id: user.id, level: 1).each_with_index do |join_user| %>
<% user_group = Group.find(join_user.group_id) %>

    <div class="card my-3" style="max-width: 500px;">
      <%= link_to group_path(user_group) do %>
        <div class="row no-gutters">
          <div class="col-6" style="max-width: 150px;">

            <%# 画像が有る場合 %>
            <% if user_group.image? %>
              <%= image_tag user_group.image.thumb.url, class: "card-img", alt:"..." %>
            <%# 画像が無い場合 %>
            <% else %>
              <img src= <%="/assets/group#{1}.png"%> class="card-img" alt="...">
            <% end %>

          </div>
          <div class="col-6">
            <div class="card-body">
              <h4 class="card-title"><%= user_group.name %></h4>
              <p class="card-text"><%= user_group.introduction %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>  
<% end %>

app/views/users/user_show/_permits.html.erb
  <!-- 承認中のグループを情報を表示 -->
<% Group.where(adminuser_id: user.id).each_with_index do |adiminuser_group| %>
  <% Join.where(group_id: adiminuser_group.id).where.not(level: 1).each_with_index do |join_permit| %>
  <% permit_user = User.find(join_permit.user_id) %>

    <%#= link_to edit_group_join_path(user_group,join_user) do %>
      <div class="card my-3" style="max-width: 500px;"> <!-- max-height: 75px;-->
        <div class="row no-gutters">
          <div class="col-lg-4" style="max-width: 100%;">

            <%# 画像が有る場合 %>
            <% if permit_user.image? %>
              <%= image_tag permit_user.image.thumb.url, class: "card-img", alt:"..." %>
            <%# 画像が無い場合 %>
            <% else %>
              <img src= <%="/assets/gest.png"%> class="card-img" alt="...">
            <% end %>

          </div>
          <div class="col-lg-8">
            <div class="card-body">
              <h4 class="card-title"><%= link_to permit_user.name, user_path(permit_user) %></h4>
              <p class="card-text"><%= adiminuser_group.name %></p>
              <p class="card-text"><%= join_permit.level %></p>
              <p class="card-text"><%= join_permit.content %></p>
              <%#= link_to edit_group_join_path(permit_user,join_user) %>
              <%= link_to group_join_path(adiminuser_group,join_permit) do %>
                <i class="far fa-address-card" style="font-size:2em"></i>
              <% end %>
              <%= link_to permit_group_join_path(adiminuser_group,join_permit) do %>
              <i class="fas fa-user-plus" style="font-size:2em"></i>
              <% end %>
              <%= link_to group_join_path(adiminuser_group,join_permit), method: :delete do %>
                <i class="far fa-trash-alt text-right" style="font-size:2em"></i>
              <% end %>
            </div>
          </div>
        </div>
      </div>  
  <% end %>
<% end %>

app/views/users/user_show/_profile.html.erb
<!-- ユーザー情報を表示 -->
<div class="card my-3" style="max-width: 500px;">
  <%= link_to user_path(user) do %>
  
  <div class="row no-gutters">
    <%# 画像ファイルの有無で処理を分岐 %>
    <div class="col-6" style="max-width: 150px;">
      <%# 有る場合 %>
      <% if user.image? %>
        <%= image_tag user.image.thumb.url, class: "card-img", alt:"..." %>
      <%# 無い場合 %>
      <% else %>
          <img src= <%="/assets/gest.png"%> class="card-img" alt="...">
      <% end %>
    </div>

    <div class="col-6">
      <div class="card-body">
          <h4 class="card-title"><%= user.name %></h4>
          <p class="card-text"><%= user.email %></p>
      </div>
    </div>
  </div>
  <% end %>
</div>

<%# current_userを判別して分岐 %>
<%# 自分自身の場合 %>
  <% if @user.id == @current_user.id %>
    <div class="row form-group mt-3">
      <div class="col-lg-11"></div>
      <div class="col-lg-1"><%= link_to '編集', edit_user_path(@user), class: 'btn btn-outline-info'%></div>
    </div>
    <div class="row form-group mt-3">
      <div class="col-lg-11"></div>
      <div class="col-lg-1"><%= link_to '削除', user_path(@user), class: 'btn btn-outline-danger', method: :delete %></div>
      <div class="col-lg-4"></div>
    </div>
<%# 他のユーザの場合 %>
  <% else %>
  <% end %>

app/views/users/user_show/_requests.html.erb
  <!-- 申請中のグループを情報を表示 -->
<% Join.where(user_id: user.id).where.not(level: 1).each_with_index do |join_user| %>
<% user_group = Group.find(join_user.group_id) %>

  <%#= link_to edit_group_join_path(user_group,join_user) do %>
    <div class="card my-3" style="max-width: 500px;"> <!-- max-height: 75px;-->
      <div class="row no-gutters">
        <div class="col-lg-4" style="max-width: 100%;">

          <%# 画像が有る場合 %>
          <% if user_group.image? %>
            <%= image_tag user_group.image.thumb.url, class: "card-img", alt:"..." %>
          <%# 画像が無い場合 %>
          <% else %>
            <img src= <%="/assets/group#{1}.png"%> class="card-img" alt="...">
          <% end %>

        </div>
        <div class="col-lg-8">
          <div class="card-body">
            <h4 class="card-title"><%= user_group.name %></h4>
            <p class="card-text"><%= join_user.level %></p>
            <p class="card-text"><%= join_user.content %></p>
            <%#= link_to edit_group_join_path(user_group,join_user) %>
            <%= link_to edit_group_join_path(user_group,join_user) do %>
              <i class="fas fa-edit" style="font-size:2em"></i>
            <% end %>
            <%= link_to group_join_path(user_group,join_user), method: :delete do %>
              <i class="far fa-trash-alt text-right" style="font-size:2em"></i>
            <% end %>
          </div>
        </div>
      </div>
    </div>  
  <%# end %>
<% end %>