config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 「SPA用のrouting」
  root 'home#index' #'groups#index'

  #group関連
  get '/groups/', to: 'home#index'
  get '/groups/new', to: 'home#index'
  get '/groups/:id', to: 'home#index'
  get '/groups/:id/detail', to: 'home#index'
  get '/groups/:id/events', to: 'home#index'
  get '/groups/:id/member', to: 'home#index'
  get '/groups/:id/edit', to: 'home#index'

  #approval関連
  get '/groups/:id/approval', to: 'home#index'
  get '/groups/:id/joins/:join_id/permit', to: 'home#index'

  #evnet関連
  get '/groups/:id/events/new', to: 'home#index'
  get '/groups/:id/events/:event_id', to: 'home#index'
  get '/groups/:id/events/:event_id/edit', to: 'home#index'

  #join関連
  get '/groups/:id/joins/new', to: 'home#index'
  get '/groups/:id/joins/:join_id/edit', to: 'home#index'

  #user関連
  get '/login', to: 'home#index'

  get '/users/', to: 'home#index'
  get '/users/new', to: 'home#index'
  get '/users/:id', to: 'home#index'
  get '/users/:id/profile', to: 'home#index'
  get '/users/:id/application', to: 'home#index'
  get '/users/:id/edit', to: 'home#index'
  get '/users/:id/event', to: 'home#index'
  get '/users/:id/favorite', to: 'home#index'
  
  #application関連
  get '/users/:id/application', to: 'home#index'

  #「API用のrouting」

  # resources :users
  resources :answers #, :only => [:show, :edit ] 

  namespace :api, {format: 'json'} do
    namespace :v1 do

      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/login', to: 'sessions#destroy'
      post 'guest_login', to: "users#guest_login" #簡単ログイン用に追加 1/20

      resources :users

      resources :answers #, :only => [:show, :edit ]  //ここを追記

      resources :groups do #do
        #member do 2/6 削除 join controller に移行
          #get :join
        #end

        # resources :favorites , only: [:create, :destroy]
        get '/favorites', to: 'favorites#index'
        post 'favorites', to: 'favorites#create'
        delete 'favorites', to: 'favorites#destroy'

        resources :joins, param: :join_id do #2/6 join controller作成のため追記
          member do 
            get :permit
            delete :leave #3/2 join leave処理の追加
            delete :deny #9/2 申請拒否の追加
          end 
        end
        resources :events, param: :event_id # 7/15 GoupEventで一覧が必要なためコメントアウト, :except => [:index ] 
      end

    end
  end

end

app/models/group.rb
class Group < ApplicationRecord

# ==============画像uploader機能 ================================
  mount_uploader :image, ImageUploader
# ==============バリデーション ================================
  #グループ情報は未入力は不可
  with_options presence: true do
    validates :name
    validates :introduction
  end
  #groupの名前にvalidateをかける
  validates :name, length: {maximum: 10}  
  validates :name, uniqueness: true       #nameは重複不可

# ==============アソシエーション ================================
  #favorite用 (多対多)
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  #join用 (多対多)
  has_many :joins, dependent: :destroy
  has_many :users, through: :joins
  #event用(1対多) (Groupv対Event)
  has_many :events, dependent: :destroy
end

app/controllers/api/v1/groups_controller.rb
class Api::V1::GroupsController < ApplicationController
  protect_from_forgery #追記
  before_action :logged_in_user, only: %i[show new edit update destroy join] #ログイン後しか実行できないアクション
  before_action :set_target_group, only: %i[show edit update destroy join]
  before_action :admin_user, only: %i[edit update destroy] #幹事でないと操作できないアクション

  def index
    #--------------------N+1改善ver--------------------
    @groups = Group.includes(:joins).order(id: :asc)
    @groups_length = []
    @groups.each do |group|
      @groups_length << {
        id: group.id, count: group.joins.where(level: '1').length
      }
    end

    #--------------------元々のコード--------------------
    # @groups = Group.order(id: :asc) #idの昇順に表示
    # @groups_length = []
    # Group.preload(:users).all.each do |group|
    #   @groups_length << {
    #     id: group.id, count: group.joins.where(level: '1').length
    #   }
    # end

    # @test = @groups_length2 === @groups_length

    render json: {groups: @groups, current_user: current_user, groups_length: @groups_length }
  end

  def show
    #--------------------N+1改善ver--------------------
    @all_joins = Join.includes(:user).where(group_id: @group.id)

    #Group所属済のuserを取得
    @joins = @all_joins.where(level: '1')

    @admin_user = User.find_by(id: @group.adminuser_id) 
    @users = []
    @joins.each do |join|
        @users.push(join.user)
    end

    #承認中のデータ,user情報を取得
    @approvals = @all_joins - @joins

    @approval_users = []
    @approvals.each do |approval|
      @approval_users.push(approval.user)
    end

    @approval_users_count = @approval_users.length
    # #--------------------元々のコードたち--------------------
    # @all_joins = Join.where(group_id: @group.id)
    
    # #Group所属済のuserを取得
    # @joins = @all_joins.where(level: '1')
    # # @joins = Join.where(group_id: @group.id).where(level: '1')
    # @users = []
    # for @join in @joins do
    #     @user = User.find_by(id: @join.user_id)
    #     @users.push(@user)
    # end
    # @admin_user = User.find_by(id: @group.adminuser_id) 

    # #承認中のデータ,user情報を取得
    # @approvals = @all_joins - @joins
    # # @approvals = Join.where(group_id: @group.id).where(level: '2')
    # @approval_users = []
    # for @approval in @approvals do
    #   @approval_user = User.find_by(id: @approval.user_id)
    #   @approval_users.push(@approval_user)
    # end

    # @test = @approval_users.length == @approval_users2.length

    # render json: {group: @group, users: @users, admin_user: @admin_user, approvals: @approvals, approval_users: @approval_users, current_user: current_user, all_joins: @all_joins }

    render json: {
      group: @group, 
      users: @users, 
      admin_user: @admin_user, 
      approvals: @approvals, 
      approval_users: @approval_users, 
      current_user: current_user, 
      all_joins: @all_joins, 
      joins: @joins, 
      approval_users_count: @approval_users_count
    }
  end

  def new
    @group = Group.new
    render json: {group: @group, current_user: current_user }
  end

  def create
    group = Group.new(group_params)
    current_user = User.find(group.adminuser_id)
    group.users << current_user #group_user_relationsにidを格納させる
    if group.save
      render json: group, status: :created
    else
      render json: group.errors, status: :unprocessable_entity
    end
  end

  def edit
    render json: {group: @group, current_user: current_user, redirect: @redirect }
  end

  def update
    if @group.update(group_params)
      # render json: @group, status: :created
      render json: {group: @group }, status: :created
    else
      render json: { status: 'SUCCESS', message: 'Not updated', data: @group.errors }
    end
  end

  def destroy
    @group.destroy
    render json: { status: 'SUCCESS', message: 'Deleted the post', data: @group }
  end

private

  def group_params
    # params.require(:group).permit(:name,:adminuser_id, :introduction, :image, :image_cache)
    params.require(:group).permit(:image, :image_cache, :name, :frequency, :lat, :lng, :instagram, :introduction,:adminuser_id)
  end

  def set_target_group
    @group = Group.find(params[:id])
  end

  #admin_userでないとrootに戻す処理
  def admin_user
    @redirect = false
    unless @group.adminuser_id == current_user.id
      # redirect_back(fallback_location: root_path) #直接urlに入力してきたユーザーはrootに戻す
      @redirect = true
    end
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :logged_in_user, only: %i[show new edit update destroy join] #ログイン後しか実行できないアクション
  before_action :set_target_group, only: %i[show edit update destroy join]
  before_action :admin_user, only: %i[edit update destroy] #幹事でないと操作できないアクション

  def index
    #@groups = Group.all
    @groups = Group.order(id: :asc) #idの昇順に表示
  end

  def show
    @users = @group.users.all #groupに所属するuserを配列で取得
    @admin_user = @users.find_by(id: @group.adminuser_id) #管理者をgroupのadminuser_idから取得
  end

  def new
    @group = Group.new
  end

  def create
    group = Group.new(group_params)
    group.adminuser_id = current_user.id #group作成中のidをgroupモデルのaddminuser_idに格納
    group.users << current_user #group_user_relationsにidを格納させる
    if group.save
      flash[:notice] = "「#{group.name}」を作成しました"
      redirect_to groups_path
    else
  #フォームの入力エラーを起こした際のエラー表示を取得するための処理
      redirect_to new_group_path, flash: {
        group: group,
        error_messages: group.errors.full_messages
      }
    end
  end

  def edit
  end

  def update
    if @group.update(group_params)
      redirect_to group_path(@group)
    else
  #フォームの入力エラーを起こした際のエラー表示を取得するための処理
      redirect_to edit_group_path, flash: {
      group: @group,
      error_messages: @group.errors.full_messages
    }
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_path, flash: { notice: "「#{@group.name}」が削除されました"}
  end

private

  def group_params
    params.require(:group).permit(:name, :introduction, :image, :image_cache)
  end

  def set_target_group
    @group = Group.find(params[:id])
  end

  #admin_userでないとrootに戻す処理
  def admin_user
    unless @group.adminuser_id == current_user.id
      redirect_back(fallback_location: root_path) #直接urlに入力してきたユーザーはrootに戻す
    end
  end

end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/group_show/_detaile.html.erb
<h3 class="my-3">グループ紹介</h3>

<%# 紹介のフォーマット %>
<div class="card mb-3">
  <div class="row no-gutters">
    <div class="col-6" style="max-width: 250px;"> <!-- style="max-width: 250px;"-->
      <%# 画像が有る場合 %>
      <% if @group.image? %>
        <%#= image_tag @group.image.thumb.url, class: "card-img", alt:"..." %>
        <%= image_tag @group.image.url, class: "card-img", alt:"..." %>
      <%# 画像が無い場合 %>
      <% else %>
        <img src= <%="/assets/cuba#{1}.jpeg"%> class="card-img" alt="...">
      <% end %>
    </div>
    <div class="col-6">
      <div class="card-body">
        <h4 class="card-title"><%= @group.name %></h4>
        <p class="card-text"><%= @group.introduction %></p>
      </div>
    </div>
  </div>
</div>

<%# current_userを判別して分岐 %>
  <%# 管理者 %>
    <% if @admin_user == current_user %>
      <div class="row form-group mt-3">
        <div class="col-lg-11"></div>
        <div class="col-lg-1"><%= link_to '編集', edit_group_path(@group), class: 'btn btn-outline-info'%></div>
      </div>
      <div class="row form-group mt-3">
        <div class="col-lg-11"></div>
        <div class="col-lg-1"><%= link_to '削除', group_path(@group), class: 'btn btn-outline-danger', method: :delete %></div>
      </div>
  <%# ユーザー %>
    <% else %>
    <%# current_userをさらに判別して分岐 %>
      <%# Join台帳に登録済み & 参加済み なら %>
      <% join_group = Join.find_by(group_id: @group.id, user_id: current_user.id)%> <%# この後の処理で必要なので格納 %>
      <% if @group.users.ids.include?(current_user.id) and join_group.level == 1 %>
        <div class="row form-group mt-3">
          <div class="col-lg-11"></div>
          <div class="col-lg-1"><%= link_to '退会', root_path , class: 'btn btn-outline-danger'%></div> 
        </div>
      <%# グループ未所属 %>
       <% elsif @group.users.ids.include?(current_user.id) %>
        <div class="row form-group mt-3">
          <div class="col-lg-11"></div>
          <div class="col-lg-1"><%= link_to '申請編集', edit_group_join_path(@group,join_group) , class: 'btn btn-outline-info'%></div> 
        </div>
      <%# join台帳未登録なら %>
      <% else %>
        <div class="row form-group mt-3">
          <div class="col-lg-11"></div>
          <div class="col-lg-1"><%= link_to '申請', new_group_join_path(@group) , class: 'btn btn-outline-info'%></div> <%# ↑ 2/6 追記 join controller 経由に移行 %>
        </div>
      <% end %>
    <% end %>

app/views/groups/group_show/_member.html.erb
<!-- 幹事の紹介 -->
<h3 class="my-3">幹事</h3>
<div class="row no-gutters">
<%# card部分 %>
  <div class="card my-3 col-lg-6" style="max-width: 500px;">
    <%= link_to user_path(group.users.find(@admin_user.id)) do %>
      <div class="row no-gutters">
        <%# 画像ファイルの有無で処理を分岐 %>
        <div class="col-6" style="max-width: 150px;">
          <%# 有る場合 %>
          <% if @admin_user.image? %>
            <%= image_tag @admin_user.image.thumb.url, class: "card-img", alt:"..." %>
          <%# 無い場合 %>
          <% else %>
              <img src= <%="/assets/cuba#{1}.jpeg"%> class="card-img" alt="...">
          <% end %>
        </div>
        <%# card-body部分 %>
        <div class="col-6">
          <div class="card-body">
            <h4 class="card-title"><%= @admin_user.name %></h4>
            <p class="card-text"><%= @admin_user.email %></p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
<%# 右側の部分 %>
  <div class=" my-3 col-lg-6">
  </div>

</div>

<!-- 幹事以外の紹介 -->
<h3 class="my-3">メンバー</h3>

<% Join.where(group_id: group.id, level: 1).each_with_index do |join_user| %>
<% group_user = User.find(join_user.user_id) %>

<%# 幹事の時はeach do を一回分進める%>
  <% if group_user.id == @admin_user.id then %>
  <% next %>
  <% end %>
    
<%# 幹事以外の処理 %>
  <div class="row no-gutters">
  <%# card部分 %>
    <div class="col-lg-6">
      <div class="card my-3" style="max-width: 500px;">
        <%= link_to user_path(group_user) do %>
          <div class="row no-gutters">
          <%# 画像ファイルの有無で処理を分岐 %>
            <div class="col-6" style="max-width: 150px;">
              <%# 画像が有る場合 %>
              <% if group_user.image? %>
                <%= image_tag group_user.image.thumb.url, class: "card-img", alt:"..." %>
            <%# 画像が無い場合 %> 
              <% else %>
                <img src= <%="/assets/gest.png"%> class="card-img" alt="...">
              <% end %>
            </div>
          <%# card-body部分 %>
            <div class="col-6">
              <div class="card-body">
                <h4 class="card-title"><%= group_user.name %></h4>
                <p class="card-text"><%= group_user.email %></p>
              </div>
            </div>
          
          </div>
        <% end %>
      </div>
    </div>
  <%# 右側部分 %> 
    <div class="col-lg-6"> 
      <div class="row no-gutters my-3">
        <div class="col-lg-6"> 
        </div>
        <%# current_userを判別して分岐 %>
        <%# 管理者 %>
        <% if @admin_user == current_user %>
          <div class="col-lg-6"> 
            <% join_user = Join.find_by(group_id: group.id, user_id: group_user.id) %>
            <%= link_to '退会', leave_group_join_path(group,join_user) , class: 'btn btn-outline-danger' , method: :delete %>
          </div>
        <%# 幹事以外のユーザー %>
        <% else %>
          <div class="col-lg-6"> 
          </div>
        <% end %>
      </div>
    </div>

  </div>
<% end %>

app/views/groups/group_show/_schedule.html.erb
<h3 class="my-3">日程</h3>

<%# 日程のフォーマット %>
<div class='text-nowrap table-responsive'>
  <table class="table table-hover boards__table table-bordered">
    <thead class="thead-light">
      <tr>
        <th>日付</th>
        <th>時間</th>
        <th>場所</th>
        <th>備考</th>
        <th>○</th>
        <% Join.where(group_id: group.id, level: 1).each_with_index do |join_user| %>
        <% group_user = User.find(join_user.user_id) %>
          <th><%= link_to group_user.name, user_path(group_user) %></th> 
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% group.events.each_with_index do |group_event| %>
        <tr>
            <td><%= link_to group_event.date.strftime( "%-m/%-d" ), group_event_path(group,group_event)  %></td> <%# 日付 %>
            <% time_s = group_event.starttime.strftime( "%H:%M" ) %> <%# 開始時間をtime_sに格納%>
            <% time_f = group_event.finishtime.strftime( "%H:%M" ) %> <%# 開始時間をtime_fに格納%>
          <td><%= "#{time_s}~#{time_f}" %></td> <%# 時間 %>
          <td><%= group_event.place %></td> <%# 場所 %>
          <td><%= group_event.remarks %></td> <%# 備考 %>
          <td><%= Answer.where(event_id: group_event, answer: "○").count %></td> <%# 参加可能の数をcount %>
          <%# eventとuserからAnswerオブジェクトを一意に収束させるための計算処理 %>
            <% Join.where(group_id: group.id, level: 1).each_with_index do |join_user| %>
            <% group_user = User.find(join_user.user_id) %>
              <% answer = Answer.find_by(event_id: group_event.id, user_id: group_user) %>
                <%# eventがない場合 %>
                <% if answer == nil %>
                <td></td>
                <%# 自分自身 %>
                <% elsif group_user == current_user %>
                  <td><%= link_to answer.answer, edit_answer_path(answer.id) %></td>
                <%# その他のユーザー %>
                <% else %>
                  <td><%= answer.answer %></td>
                <% end %>
            <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>

<%# current_userを判別して分岐 %>
    <%# 管理者 %>
  <% if @admin_user == current_user %>
    <%# 新規予定作成ボタン %>
    <div class="row form-group mt-3">
      <div class="col-lg-12"><%= link_to '+', new_group_event_path(@group), class: 'btn btn-outline-info'%></div>
    </div>
    <%# ユーザー %>
    <% else %>
  <% end %>
</div>