config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # 「SPA用のrouting」
  root 'home#index' #'groups#index'

  #group関連
  get '/groups/', to: 'home#index'
  get '/groups/new', to: 'home#index'
  get '/groups/:id', to: 'home#index'
  get '/groups/:id/detail', to: 'home#index'
  get '/groups/:id/events', to: 'home#index'
  get '/groups/:id/member', to: 'home#index'
  get '/groups/:id/edit', to: 'home#index'

  #approval関連
  get '/groups/:id/approval', to: 'home#index'
  get '/groups/:id/joins/:join_id/permit', to: 'home#index'

  #evnet関連
  get '/groups/:id/events/new', to: 'home#index'
  get '/groups/:id/events/:event_id', to: 'home#index'
  get '/groups/:id/events/:event_id/edit', to: 'home#index'

  #join関連
  get '/groups/:id/joins/new', to: 'home#index'
  get '/groups/:id/joins/:join_id/edit', to: 'home#index'

  #user関連
  get '/login', to: 'home#index'

  get '/users/', to: 'home#index'
  get '/users/new', to: 'home#index'
  get '/users/:id', to: 'home#index'
  get '/users/:id/profile', to: 'home#index'
  get '/users/:id/application', to: 'home#index'
  get '/users/:id/edit', to: 'home#index'
  get '/users/:id/event', to: 'home#index'
  get '/users/:id/favorite', to: 'home#index'
  
  #application関連
  get '/users/:id/application', to: 'home#index'

  #「API用のrouting」

  # resources :users
  resources :answers #, :only => [:show, :edit ] 

  namespace :api, {format: 'json'} do
    namespace :v1 do

      get '/login', to: 'sessions#new'
      post '/login', to: 'sessions#create'
      delete '/login', to: 'sessions#destroy'
      post 'guest_login', to: "users#guest_login" #簡単ログイン用に追加 1/20

      resources :users

      resources :answers #, :only => [:show, :edit ]  //ここを追記

      resources :groups do #do
        #member do 2/6 削除 join controller に移行
          #get :join
        #end

        # resources :favorites , only: [:create, :destroy]
        get '/favorites', to: 'favorites#index'
        post 'favorites', to: 'favorites#create'
        delete 'favorites', to: 'favorites#destroy'

        resources :joins, param: :join_id do #2/6 join controller作成のため追記
          member do 
            get :permit
            delete :leave #3/2 join leave処理の追加
            delete :deny #9/2 申請拒否の追加
          end 
        end
        resources :events, param: :event_id # 7/15 GoupEventで一覧が必要なためコメントアウト, :except => [:index ] 
      end

    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  # ログイン済みユーザーかどうか確認
   def logged_in_user
     unless logged_in?
       redirect_to login_url
     end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light" style="background-color:#afeeee;"> <%#e3f2fd%>
  <div class="container">
  <a class="navbar-brand mr-auto mt-2 mt-lg-0" href="/">Syumix</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
      <li class="nav-item">
        <a class="nav-link" href="/">ログイン</a>
      </li>
      <li class="nav-item">
        <%= link_to "ログアウト", login_path, class: 'nav-link' ,method: :delete %>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/groups/new">幹事になる</a>
      </li>
    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link" href="/">グループを探す</a>
      </li>
    </ul>
  </div>
</nav>

app/views/application/_member_BU.html.erb
<!-- 幹事の紹介 -->
<h3 class="my-3">幹事</h3>
<div class="card my-3" style="max-width: 500px;">
  <%= link_to user_path(group.users.find(@admin_user.id)) do %>

  <div class="row no-gutters">
    <%# 画像ファイルの有無で処理を分岐 %>
    <div class="col-lg-6" style="max-width: 150px;">
      <%# 有る場合 %>
      <% if @admin_user.image? %>
        <%= image_tag @admin_user.image.thumb.url, class: "card-img", alt:"..." %>
      <%# 無い場合 %>
      <% else %>
          <img src= <%="/assets/cuba#{1}.jpeg"%> class="card-img" alt="...">
      <% end %>
    </div>

    <div class="col-lg-6">
      <div class="card-body">
          <h4 class="card-title"><%= @admin_user.name %></h4>
          <p class="card-text"><%= @admin_user.email %></p>
      </div>
    </div>

  </div>
  <% end %>
</div>

<!-- 幹事以外の紹介 -->
<h3 class="my-3">メンバー</h3>
<% Join.where(group_id: group.id, level: 1).each_with_index do |join_user| %>
<% group_user = User.find(join_user.user_id) %>

    <%# 幹事の時はeach do を一回分進める%>
    <% if group_user.id == @admin_user.id then %>
    <% next %>
    <% end %>
    
    <%# 幹事以外の処理 %>
    <div class="card my-3" style="max-width: 500px;">
      <%= link_to user_path(group_user) do %>
        <div class="row no-gutters">
          <div class="col-lg-6" style="max-width: 150px;">
            <%# 画像が有る場合 %>
            <% if group_user.image? %>
              <%= image_tag group_user.image.thumb.url, class: "card-img", alt:"..." %>
           <%# 画像が無い場合 %> 
            <% else %>
              <img src= <%="/assets/gest.png"%> class="card-img" alt="...">
            <% end %>
          </div>

          <div class="col-lg-6">
            <div class="card-body">
              <h4 class="card-title"><%= group_user.name %></h4>
              <p class="card-text"><%= group_user.email %></p>
            </div>
          </div>
        
        </div>
      <% end %>
    </div>  

  <% join_user = Join.find_by(group_id: group.id, user_id: group_user.id) %>
  <div class="col-lg-1"> <%# 退会ボタン %> 
    <%= link_to '退会', leave_group_join_path(group,join_user) , class: 'btn btn-outline-danger' , method: :delete %>
  </div>

<% end %>

app/views/application/memo.html.erb
 <%# environment.jsのバックアップ @1/15に除去した部分 %>
 // 追記 21/1/6
//jQueryとBootstapのJSを使えるようにjQueryとBootstapのJSを使えるように
// const webpack = require('webpack')
// environment.plugins.prepend(
//   'Provide',
//   new webpack.ProvidePlugin({
//     $: 'jquery',
//     jQuery: 'jquery',
//     Popper: 'popper.js'
//   })
// )
// ここまで
<%# jsのテストファイル %>

    <%# jsが使用できるかのテスト%>
      <p>テスト</p>
      <script type="text/javascript">
        $(document).ready(function() {
        $("p").text("成功！！");
        });
      </script>
    <%# ここまで %>

<%# 多対多テンプレ %>
docker-compose run web bundle exec rails g model <model(中)> <model(多)1>:references <model(多)2>:references
docker-compose run web bundle exec rails g model user_group_relation user:references group:references

<%# テンプレ %>
AddColumnNullToGroups

<!-- User controller -->
docker-compose exec web rails g controller Users new show edit destroy

docker-compose run web rails g migration AddIndexToGroups

Group.where(id: 127..133).destroy_all

docker-compose run web rails g migration ChangeAdminuser_idToGroups

モデル名.columns_hash['カラム名'].type

<!-- Event -->

docker-compose run web bundle exec rails g model event group:references date:date start-time:time finish-time:time place:string maru:string batu:string remarks:text

docker-compose exec web rails g controller Events new edit show

docker-compose exec web rails destroy controller Event

<%# Answer model %>

docker-compose run web bundle exec rails g model Answer user:references event:references

<%# Answer controller %>

docker-compose exec web rails g controller Answers show edit 

docker-compose run web rails g migration change_answer_of_Answers
<%= f.select :faculty, [["理工学部", "理工学部"], ["経済学部", "経済学部"], ["法学部", "法学部"], ["医学部", "医学部"]], include_blank: "選択して下さい" %>

<%# stylesheets/application.scssの2行を消した %>
 *= require_tree .
 *= require_self

 <!-- ここからlink付きfontawesome -->
<%= link_to URLヘルパー, class: "btn btn-danger", method: :delete do %>
  <i class="far fa-trash-alt"></i> #=>　アイコンのコード
<% end %>

<%# 画像投稿機能 %>
docker-compose run web bundle exec rails g uploader image
docker-compose run web rails generate migration add_image_to_users image:string

<%# 画像表示のバックアップ %>
<div class="col-lg-6" style="max-width: 150px;">
  <img src= <%="/assets/cuba#{1}.jpeg"%> class="card-img" alt="...">
</div>

<%# 画像保存済みの場合はサムネイルを表示 %>
<div class="row no-gutters">
  <div class="col-lg-6" style="max-width: 150px;">
    <%= image_tag "#{@user.image}" if @user.image? %>
  </div>
</div>

<%# %><%#= group.index %>
<img src= <%="/assets/group#{i+1}.png"%> class="card-img-top" alt="...">


<%# ここから検索フォームのテスト %>
<%= form_tag root_path, method: :get, class: 'boards__searchForm' do %>
      <%= select_tag :tag_id,
                     options_from_collection_for_select(Group.all, :id, :introduction, params[:tag_id]),
                     {
                       prompt: 'タグで絞り込み検索',
                       onchange: 'submit(this.form);'
                     }
      %>
<% end %>

<%# group_join action のメモ %>
  #グループ参加申請処理
  def join
    #グループに参加済みの人の処理
    if @group.users.ids.include?(current_user.id) then
      redirect_to group_path(@group), flash: { notice: "#{@group.name}にはすでに参加済みです"}
    #グループに新規参加の人の処理
    else 
      @group.users << current_user #group_user_relationsにidを格納させる
      Event.where(group_id: @group.id).each_with_index do |group_event| #Eventを次々に取得 1/12編集
        group_event.users << current_user #Anserに(event_id,user_id)を紐付ける 1/12追記
      end
      redirect_to group_path(@group), flash: { notice: "「#{current_user.name}が#{@group.name}に参加しました"}
    end
  end

Private
  def set_target_group
    @group = Group.find(params[:id])
  end

<%# ターミナル記述メモ %>
docker-compose exec web rails g controller joins new edit show

docker-compose run web bundle exec rails g model Join user:references group:references

<div class="col-lg-1"><%= link_to '申請', join_group_path(@group) , class: 'btn btn-outline-info'%></div> 

docker-compose run web bundle exec rails destroy model Join

docker-compose run web rails g migration Change<旧Table名>To<新Table名>
docker-compose run web rails g migration ChangeUserGroupRelationsToJoins

docker-compose run web rails g migration Add<Column名>To<Tables名>
docker-compose run web rails g migration AddLevelToJoins

<%# %>


<%#= answer.answer %>